### ISSUE TITLE
curl problem

### ISSUE THREAD

**Issue by M4DF135H** [tommiehansen/gab#30]
hi!
I installed XAMPP with PHP version 7.1+ and wanted to use GA to select parameters, but I always get an error:
16:00:59 Runner.php ERROR: Running config via curl_post() did not return data.
url: http://localhost:3000/api/backtest | curl status: 0 - No data

Prompt, please, in what there can be a problem?

**Comment by Gutz-Pilz** [comment]
i got the same problem on my debian system.
can you give me a hint - i'd like to try to fix it myself. 
really love your software !

**Comment by SirTificate** [comment]
This might be a compatibility issue with the lastest 0.6.x releases of gekko. it's fixed now. 
Please get the latest version of GAB and reopen this issue if the error persists.

**Comment by itsXactlY** [comment]
Hey, same issue on Debian 9 Stable, Lamp, PHP 7.3. Gekko and GaB are Up2Date and just cloned couple days ago.

 xxx POST /api/backtest 500 87s -

  Error: non-error thrown:
   ERROR: Query returned no candles (do you have local data for the specified range?)

      at Object.onerror (/home/alca/public_html/gekko/node_modules/koa/lib/context.js:105:40)
      at process._tickCallback (internal/process/next_tick.js:68:7)

uncaughtException { TypeError: Cannot read property 'start' of undefined
    at Market.processCandles (/home/alca/public_html/gekko/core/markets/backtest.js:87:34)
    at bound (/home/alca/public_html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/alca/public_html/gekko/plugins/sqlite/reader.js:108:5)
--> in Database#all('\n    SELECT * from candles_USDT_BNB\n    WHERE start <= 1580779859 AND start >= 1580776860\n    ORDER BY start ASC\n  ', [Function])
    at Reader.get (/home/alca/public_html/gekko/plugins/sqlite/reader.js:98:11)
    at Reader.bound [as get] (/home/alca/public_html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.get (/home/alca/public_html/gekko/core/markets/backtest.js:61:15)
    at Market.bound [as get] (/home/alca/public_html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Market.processCandles (/home/alca/public_html/gekko/core/markets/backtest.js:105:10)
    at bound (/home/alca/public_html/gekko/node_modules/lodash/dist/lodash.js:729:21)
    at Statement.<anonymous> (/home/alca/public_html/gekko/plugins/sqlite/reader.js:108:5) __augmented: true }
  <-- POST /api/backtest
  xxx POST /api/backtest 500 106s -

  Error: non-error thrown:
   ERROR: Query returned no candles (do you have local data for the specified range?)

Im not a expert at this weird debug messages, but guess my settings i set are totaly weird, whats causing this?!
