### ISSUE TITLE
Another "Uncaught Exception: Unknown primative for `'no'` on line 2."

### ISSUE THREAD

**Issue by WilbertNL** [tommiehansen/gab#31]
Sorry to re-address this issue, but I'm encountering the same problem as in #4 :
```
Fatal error:  Uncaught Exception: Unknown primative for `'no'` on line 2. in /var/www/html/gab/system/class.toml.php:176
Stack trace:
#0 /var/www/html/gab/system/class.toml.php(121): Toml\Parser->parseValue(''no'')
#1 /var/www/html/gab/system/class.toml.php(78): Toml\Parser->processLine('buyImmediately ...')
#2 /var/www/html/gab/system/class.toml.php(24): Toml\Parser->parse()
#3 /var/www/html/gab/system/class.gab.php(178): Toml\Parser::fromString('buyImmediately ...')
#4 /var/www/html/gab/system/class.gab.php(67): GAB\core->parse_toml('buyImmediately ...')
#5 /var/www/html/gab/system/runner.php(42): GAB\core->get_strategies()
#6 {main}
  thrown in /var/www/html/gab/system/class.toml.php on line 176
```

Freshly installed today. Already tried a newly created dataset.
Sanity check looks happy:
```
PHP EXTENSIONS
OK
DIRECTORY CREATION TEST
OK
PHP VERSION
OK You are running: 7.2.10-0ubuntu0.18.04.1
PHP MEMORY
OK Your PHP has 512M available
PHP MAX EXECUTION TIME
OK Your max execution time is 900 seconds (15 minutes)
SQLITE CREATE DATABASE TEST
OK
SQLITE INSERT TEST
OK
```
Initially I had MySQL, same problem, so now I'm trying with sqlite.

Any ideas perhaps? And where would I find the logging that izevar mentioned:
```
Gekko says:
--> POST /api/backtest 200 2,579ms 39.34kb
<-- POST /api/backtest
2018-03-24 10:17:51 (INFO):	Setting up Gekko in backtest mode
2018-03-24 10:17:51 (INFO):
2018-03-24 10:17:51 (INFO):	Setting up:
2018-03-24 10:17:51 (INFO):	Trading Advisor
```
I'm running gekko --ui. (v0.6.8). Backtests in Gekko UI work fine.

Hopefully someone can help me :-)

Thanks!

**Comment by SirTificate** [comment]
There is something wrong with your TOML config. Paste and I'll have a look.

**Comment by tommiehansen** [comment]
This can also happen when Gekko has strategies or any TOML file that contains errors (even if it isn't even the one your running). So you could also try to simply remove all other strategies except 1 (that you know does work) and re-test.

**Comment by Tetrokun** [comment]
@WilbertNL I was having the same symptoms
Tommie's advise fixed my issue, If you're using xffff's bulk strategies GAB Doesn't like some of them, I've solved this by moving all  Tomls I didn't use in gekko/config/startagies and moved them to another folder, Then it worked.

**Comment by Lusofreak** [comment]
> @WilbertNL I was having the same symptoms
> Tommie's advise fixed my issue, If you're using xffff's bulk strategies GAB Doesn't like some of them, I've solved this by moving all Tomls I didn't use in gekko/config/startagies and moved them to another folder, Then it worked.

See at the bottom of this forum page, strat with issue ;)

https://forum.gekko.wizb.it/printthread.php?tid=56589&page=9
